services:
  - type: web
    name: dcu-news-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri_here
      - key: JWT_SECRET_KEY
        value: supersecretjwtkey123
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "10080"
    autoDeploy: true
    region: oregon
    plan: free
    rootDir: backend
